const STORE_KEY='fantasy-war-room-v41-state';
const OVERRIDE_KEY='fantasy-war-room-v41-rank-tier-overrides';
const AUTH_KEY='fantasy-war-room-auth-mode-v37';
const MANUAL_SLEEPERS_KEY='fantasy-war-room-manual-sleepers-v41';
const TABLE=window.SUPABASE_TABLE||'fantasy_players';
const POSITIONS=['QB','RB','WR','TE','K','DST'];
const ADMIN_USER='admin', ADMIN_PASS='tqsd26', GUEST_PASS='password';
let state={players:[],activePos:'ALL'}, seedPlayers=[], seedById=new Map(), seedByName=new Map();
let sb=null, usingSupabase=false, realtimeChannel=null, currentRecommendation=null;
const rankEditor={active:'ALL',undoStack:[],dragId:null,dragging:false};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function uid(name){return String(name||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function key(v){return String(v||'').toLowerCase().trim()}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function parseInfo(notes){if(!notes)return{};if(typeof notes==='object')return notes;try{return JSON.parse(notes)}catch{return{}}}
function fmt(n){return Number.isInteger(Number(n))?Number(n):Number(n||0).toFixed(1)}
function authMode(){return localStorage.getItem(AUTH_KEY)||''}function isAdmin(){return authMode()==='admin'}function isGuest(){return authMode()==='guest'}
function configured(){const u=String(window.SUPABASE_URL||'').trim(),k=String(window.SUPABASE_PUBLIC_KEY||window.SUPABASE_ANON_KEY||'').trim();if(k&&!window.SUPABASE_PUBLIC_KEY)window.SUPABASE_PUBLIC_KEY=k;return u&&k&&u.startsWith('https://')}
async function init(){bindBasic();await waitForAuth();await loadSeed();await connect();render();setupRankEditor();refreshBestRecommendation();selectionGuard();applyAuthUI();}
function waitForAuth(){if(authMode())return Promise.resolve();showAuthGate();return new Promise(r=>document.addEventListener('auth-ready',r,{once:true}))}
function showAuthGate(){const gate=document.createElement('div');gate.className='auth-gate';gate.innerHTML=`<div class="auth-card"><div class="eyebrow">Fantasy Draft War Room</div><h2>Sign in to access draft board</h2><p class="muted">Admin can edit and save. Guest is read-only and requires guest password.</p><div class="auth-tabs"><button id="authAdminTab" class="active">Admin</button><button id="authGuestTab">Guest</button></div><div id="adminPanel"><label>Username<input id="authUser"></label><label>Password<input id="authPass" type="password"></label><div id="authErr" class="auth-error" hidden>Invalid admin username or password.</div><button id="authLogin" style="width:100%;margin-top:12px">Login as Admin</button></div><div id="guestPanel" hidden><label>Guest Password<input id="guestPass" type="password"></label><div id="guestErr" class="auth-error" hidden>Invalid guest password.</div><button id="guestLogin" class="guest-btn" style="width:100%;margin-top:12px">Continue as Guest</button></div></div>`;document.body.appendChild(gate);const adminTab=$('#authAdminTab'),guestTab=$('#authGuestTab'),admin=$('#adminPanel'),guest=$('#guestPanel');function tab(g){admin.hidden=g;guest.hidden=!g;adminTab.classList.toggle('active',!g);guestTab.classList.toggle('active',g);setTimeout(()=>$(g?'#guestPass':'#authUser').focus(),20)}adminTab.onclick=()=>tab(false);guestTab.onclick=()=>tab(true);function loginAdmin(){if($('#authUser').value.trim().toLowerCase()===ADMIN_USER&&$('#authPass').value===ADMIN_PASS){localStorage.setItem(AUTH_KEY,'admin');gate.remove();document.dispatchEvent(new CustomEvent('auth-ready'))}else{$('#authErr').hidden=false;$('#authPass').value='';$('#authPass').focus()}}function loginGuest(){if($('#guestPass').value===GUEST_PASS){localStorage.setItem(AUTH_KEY,'guest');gate.remove();document.dispatchEvent(new CustomEvent('auth-ready'))}else{$('#guestErr').hidden=false;$('#guestPass').value='';$('#guestPass').focus()}}$('#authLogin').onclick=loginAdmin;$('#guestLogin').onclick=loginGuest;$('#authPass').onkeydown=e=>{if(e.key==='Enter')loginAdmin()};$('#guestPass').onkeydown=e=>{if(e.key==='Enter')loginGuest()};setTimeout(()=>$('#authUser').focus(),50)}
async function loadSeed(){const data=await(await fetch('excel-seed-v41.json?v=41')).json();seedPlayers=normalizeRows(data.players||[]);seedById=new Map();seedByName=new Map();seedPlayers.forEach(p=>{seedById.set(key(p.id),p);seedByName.set(key(p.name),p)})}
function normalizeRows(rows){return rows.map(p=>{const info=p.player_info||parseInfo(p.notes);return{id:p.id||uid(p.name),name:p.name,team:p.team||'',pos:p.pos||'RB',custom_rank:Number(p.custom_rank??p.rank??info['Consensus Rank']??999),rank:Number(p.rank??p.custom_rank??info['Consensus Rank']??999),tier:Number(p.tier??99),sources:p.sources||{},player_info:info,notes:p.notes||JSON.stringify(info),drafted:!!p.drafted,draftedBy:p.draftedBy??p.drafted_by??'',pick:p.pick??null}})}
function getInfoForPlayer(p){return {...(seedById.get(key(p.id))?.player_info||{}),...(seedByName.get(key(p.name))?.player_info||{}),...(p.player_info||{})}}
function buildState(existing=[]){const old=normalizeRows(existing||[]),byId=new Map(old.map(p=>[key(p.id),p])),byName=new Map(old.map(p=>[key(p.name),p]));state.players=seedPlayers.map(sp=>{const o=byId.get(key(sp.id))||byName.get(key(sp.name));return{...sp,custom_rank:o?.custom_rank??sp.custom_rank,tier:o?.tier??sp.tier,drafted:!!o?.drafted,draftedBy:o?.draftedBy||'',pick:o?.pick??null,player_info:sp.player_info,notes:JSON.stringify(sp.player_info)}});applyOverrides();localSave(false)}
async function connect(){try{if(configured()&&window.supabase){sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLIC_KEY);usingSupabase=true;const {data,error}=await sb.from(TABLE).select('*').order('custom_rank',{ascending:true});if(error)throw error;buildState(data||[]);if(isAdmin())await persistMany(state.players,false);subscribeRealtime();setStatus('Connected to Supabase.','ok')}else{await loadLocalOrSeed();setStatus('Supabase not connected. Local save only.','warn')}}catch(e){console.error(e);usingSupabase=false;await loadLocalOrSeed();setStatus('Supabase connection failed: '+(e.message||e),'bad')}}
async function loadLocalOrSeed(){const saved=localStorage.getItem(STORE_KEY);if(saved){try{buildState(JSON.parse(saved).players||[]);return}catch(e){}}buildState([])}
function toDb(p){return{id:p.id,name:p.name,team:p.team,pos:p.pos,custom_rank:Number(p.custom_rank),tier:Number(p.tier),sources:p.sources||{},notes:JSON.stringify(getInfoForPlayer(p)),drafted:!!p.drafted,drafted_by:p.draftedBy||'',pick:p.pick||null,updated_at:new Date().toISOString()}}
function localSave(stamp=true){localStorage.setItem(STORE_KEY,JSON.stringify(state));saveOverrides();if(stamp&&$('#lastSaved'))$('#lastSaved').textContent='Saved '+new Date().toLocaleTimeString()}
function saveOverrides(){const o={};state.players.forEach(p=>o[p.id]={custom_rank:p.custom_rank,tier:p.tier});localStorage.setItem(OVERRIDE_KEY,JSON.stringify(o))}
function applyOverrides(){let o={};try{o=JSON.parse(localStorage.getItem(OVERRIDE_KEY)||'{}')}catch{}state.players.forEach(p=>{if(o[p.id]){p.custom_rank=Number(o[p.id].custom_rank)||p.custom_rank;p.tier=Number(o[p.id].tier)||p.tier}})}
function assertAdmin(){if(isAdmin())return true;setStatus('Guest mode is read-only. Login as admin to save changes.','warn');return false}
async function persistPlayer(p){if(!assertAdmin())return;localSave();if(usingSupabase&&sb){const {error}=await sb.from(TABLE).upsert(toDb(p));if(error)setStatus('Supabase save failed: '+error.message,'bad')}}
async function persistMany(players=state.players,show=true){if(!assertAdmin())return;localSave();if(usingSupabase&&sb){const {error}=await sb.from(TABLE).upsert(players.map(toDb));if(error)setStatus('Supabase save failed: '+error.message,'bad');else if(show)setStatus('Saved to Supabase.','ok')}}
function subscribeRealtime(){if(!sb)return;if(realtimeChannel)sb.removeChannel(realtimeChannel);realtimeChannel=sb.channel('fantasy_players').on('postgres_changes',{event:'*',schema:'public',table:TABLE},p=>{if(isAdmin())return;connect()}).subscribe()}
function bindBasic(){['search','statusFilter','sortBy'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{render();refreshBestRecommendation()}));$('#bestBtn').onclick=refreshBestRecommendation;$('#chooseRecommendedBtn').onclick=draftRecommended;$('#editRanksBtn').onclick=openRankEditor;$('#backToDraftBtn').onclick=closeRankEditor;$('#undoRankChangeBtn').onclick=undoRankChange;$('#resetDraftBtn').onclick=resetAllDraft;$('#seedSupabaseBtn').onclick=seedSupabase;$('#refreshSourcesBtn').onclick=refreshSources;$('#sleeperPicksBtn').onclick=showSleeperPicks;$('#exportCsvBtn').onclick=exportCsv;$('#printPdfBtn').onclick=()=>window.print();$('#importAny').onchange=e=>importAny(e.target.files[0]);$('#cancelEdit').onclick=()=>$('#editDialog').close();$('#editForm').onsubmit=saveEdit;$('#closePlayerInfoBtn').onclick=()=>$('#playerInfoDialog').close();$('#closeSleeperBtn').onclick=()=>$('#sleeperDialog').close();$('#rankSearch').addEventListener('input',rankSearchInput);$('#rankSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const b=$('#rankSuggestions [data-jump-id]');if(b)jumpToRankPlayer(b.dataset.jumpId)}})}
function setStatus(msg,cls='ok'){const el=$('#syncStatus');if(el){el.textContent=msg;el.className='sync-status '+cls}}
function applyAuthUI(){document.body.classList.toggle('admin-mode',isAdmin());document.body.classList.toggle('guest-mode',!isAdmin());let wrap=$('#authStatus');if(!wrap){wrap=document.createElement('div');wrap.id='authStatus';wrap.className='auth-status';$('.top-actions').appendChild(wrap)}wrap.innerHTML=isAdmin()?'<span class="auth-chip admin">Admin</span><button id="logoutBtn">Logout</button>':'<span class="auth-chip guest">Guest View</span><button id="logoutBtn">Login</button>';$('#logoutBtn').onclick=()=>{localStorage.removeItem(AUTH_KEY);location.reload()};['editRanksBtn','resetDraftBtn','seedSupabaseBtn','refreshSourcesBtn'].forEach(id=>{const el=$('#'+id);if(el)el.hidden=!isAdmin()});$$('.file-btn').forEach(el=>el.hidden=!isAdmin())}
function sourceAvg(p){const vals=Object.values(p.sources||{}).map(Number).filter(Number.isFinite);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:p.custom_rank}
function teamCounts(){return state.players.filter(p=>p.draftedBy==='Me').reduce((a,p)=>{a[p.pos]=(a[p.pos]||0)+1;return a},{QB:0,RB:0,WR:0,TE:0,K:0,DST:0})}function availablePlayers(){return state.players.filter(p=>!p.drafted)}function currentPick(){return state.players.filter(p=>p.drafted).length+1}function posRank(p){const same=state.players.filter(x=>x.pos===p.pos).sort((a,b)=>a.custom_rank-b.custom_rank);return p.pos+(same.findIndex(x=>x.id===p.id)+1)}
function recommendationScore(p){const c=teamCounts();let s=1000-p.custom_rank*5+Math.max(0,90-p.tier*8);if(p.pos==='RB'&&c.RB<3)s+=50;if(p.pos==='WR'&&c.WR<4)s+=42;if(p.pos==='TE'&&c.TE<1)s+=25;if(p.pos==='QB'&&c.QB<1&&currentPick()>45)s+=20;if(['K','DST'].includes(p.pos)&&currentPick()<105)s-=90;return Math.round(s)}
function bestAvailable(){return availablePlayers().sort((a,b)=>recommendationScore(b)-recommendationScore(a)||a.custom_rank-b.custom_rank)[0]||null}
function getFiltered(){let arr=[...state.players];const q=key($('#search').value);if(state.activePos!=='ALL')arr=arr.filter(p=>p.pos===state.activePos);if(q)arr=arr.filter(p=>key(p.name+' '+p.team+' '+p.pos).includes(q));const st=$('#statusFilter').value;if(st==='available')arr=arr.filter(p=>!p.drafted);if(st==='mine')arr=arr.filter(p=>p.draftedBy==='Me');if(st==='drafted')arr=arr.filter(p=>p.drafted);const sort=$('#sortBy').value;arr.sort((a,b)=>sort==='recommendation'?recommendationScore(b)-recommendationScore(a)||a.custom_rank-b.custom_rank:sort==='tier'?a.tier-b.tier||a.custom_rank-b.custom_rank:sort==='adp'?sourceAvg(a)-sourceAvg(b):sort==='pos'?a.pos.localeCompare(b.pos)||a.custom_rank-b.custom_rank:a.custom_rank-b.custom_rank);return arr}
function render(){renderChips();renderScarcity();const tbody=$('#board tbody');tbody.innerHTML='';for(const p of getFiltered()){const tr=document.createElement('tr');tr.className=p.drafted?'drafted-row':'';const ro=isAdmin()?'':'disabled readonly';tr.innerHTML=`<td><div class="compact-player-line"><span class="player-name">${esc(p.name)}</span><span class="pos ${p.pos}">${posRank(p)}</span><span>${esc(p.team)}</span><button class="tile-note-btn" data-info-id="${p.id}">📝</button></div><div class="meta">${p.drafted?p.draftedBy==='Me'?'On my team':'Drafted by other':'Available'}</div><div class="mobile-metrics"><span class="metric-pill">Rank <b>${p.custom_rank}</b></span><span class="metric-pill">Tier <b>${p.tier}</b></span><span class="metric-pill">Score <b>${recommendationScore(p)}</b></span></div></td><td><input class="rank-input" type="number" value="${p.custom_rank}" data-field="custom_rank" data-id="${p.id}" ${ro}></td><td><input class="tier-input" type="number" value="${p.tier}" data-field="tier" data-id="${p.id}" ${ro}></td><td><b>${fmt(sourceAvg(p))}</b></td><td><span class="score-pill">${recommendationScore(p)}</span></td><td>${isAdmin()?`<div class="actions"><button class="mine" data-act="mine" data-id="${p.id}">Mine</button><button class="gone" data-act="gone" data-id="${p.id}">Gone</button><button class="edit" data-act="edit" data-id="${p.id}">Edit</button></div>`:'<span class="guest-readonly">View only</span>'}</td>`;tbody.appendChild(tr)}$$('.tile-note-btn').forEach(b=>b.onclick=e=>{e.preventDefault();showPlayerInfo(b.dataset.infoId)});if(isAdmin()){$$('.actions button').forEach(b=>b.onclick=()=>act(b.dataset.act,b.dataset.id));$$('.rank-input,.tier-input').forEach(i=>i.onchange=()=>inlineUpdate(i))}renderSidebars();applyAuthUI()}
function renderChips(){const wrap=$('#positionChips');wrap.innerHTML='';['ALL',...POSITIONS].forEach(pos=>{const b=document.createElement('button');b.className='chip '+(state.activePos===pos?'active':'');b.textContent=pos;b.onclick=()=>{state.activePos=pos;localSave(false);render();refreshBestRecommendation()};wrap.appendChild(b)})}
function renderScarcity(){const c=teamCounts();$('#rosterBuild').innerHTML=`<div class="meta">Current roster: QB ${c.QB||0} | RB ${c.RB||0} | WR ${c.WR||0} | TE ${c.TE||0} | K ${c.K||0} | DST ${c.DST||0}</div>`;$('#scarcityGrid').innerHTML=POSITIONS.map(pos=>{const n=availablePlayers().filter(p=>p.pos===pos).length;return`<div class="scarcity-tile"><div class="scarcity-pos ${pos}">${pos}</div><div class="scarcity-total">${n}</div><div class="meta">Available</div></div>`}).join('')}
function renderSidebars(){const mine=state.players.filter(p=>p.draftedBy==='Me').sort((a,b)=>(a.pick||999)-(b.pick||999)),drafted=state.players.filter(p=>p.drafted).sort((a,b)=>(a.pick||999)-(b.pick||999));$('#myTeam').innerHTML=mine.map(p=>`<li><b>${esc(p.name)}</b> <span class="meta">${p.pos} ${p.team}</span></li>`).join('')||'<li class="meta">No picks yet</li>';$('#liveDraftBoard').innerHTML=drafted.map(p=>`<li><span class="meta">${p.pick||''}</span> ${esc(p.name)} <span class="meta">${p.draftedBy}</span></li>`).join('')||'<li class="meta">No picks yet</li>';$('#draftedLog').innerHTML=drafted.slice(-20).reverse().map(p=>`<li>${esc(p.name)} <span class="meta">${p.draftedBy}</span></li>`).join('')||'<li class="meta">No drafted players yet</li>';$('#availableCount').textContent=availablePlayers().length;$('#myCount').textContent=mine.length;$('#draftedCount').textContent=drafted.length}
function showPlayerInfo(id){const p=state.players.find(x=>x.id===id);if(!p)return;const info=getInfoForPlayer(p);const rows=['Consensus Rank','Consensus Tier','FantasyPros ECR','Draft Sharks (3D)','Rotoworld Top 200','Avg ADP'];$('#playerInfoContent').innerHTML=`<h2>${esc(p.name)}</h2><div><span class="pos ${p.pos}">${p.pos}</span> <b>${esc(p.team)}</b></div><div class="player-info-grid">${rows.map(k=>`<div><span>${k}</span><b>${esc(info[k]??'')}</b></div>`).join('')}</div><h3>Key Player Notes & Analysis</h3><p>${esc(info['Key Player Notes & Analysis']||'No notes loaded.')}</p>`;$('#playerInfoDialog').showModal()}
function inlineUpdate(inp){if(!assertAdmin())return;const p=state.players.find(x=>x.id===inp.dataset.id);p[inp.dataset.field]=Number(inp.value);persistPlayer(p);render();refreshBestRecommendation()}
function nextPick(){return Math.max(0,...state.players.map(p=>p.pick||0))+1}function act(action,id){if(!assertAdmin())return;const p=state.players.find(x=>x.id===id);if(action==='mine'){p.drafted=true;p.draftedBy='Me';p.pick=nextPick()}if(action==='gone'){p.drafted=true;p.draftedBy='Other';p.pick=nextPick()}if(action==='edit')return openEdit(p);persistPlayer(p);render();refreshBestRecommendation()}function openEdit(p){$('#editId').value=p.id;$('#editName').value=p.name;$('#editTeam').value=p.team;$('#editPos').value=p.pos;$('#editRank').value=p.custom_rank;$('#editTier').value=p.tier;$('#editDialog').showModal()}function saveEdit(e){e.preventDefault();if(!assertAdmin())return;const p=state.players.find(x=>x.id===$('#editId').value);Object.assign(p,{name:$('#editName').value,team:$('#editTeam').value,pos:$('#editPos').value,custom_rank:+$('#editRank').value,tier:+$('#editTier').value});persistPlayer(p);$('#editDialog').close();render();renderRankEditor();refreshBestRecommendation()}
async function resetAllDraft(){if(!assertAdmin())return;if(!confirm('Reset entire draft board?'))return;state.players.forEach(p=>{p.drafted=false;p.draftedBy='';p.pick=null});await persistMany();render();refreshBestRecommendation()}async function seedSupabase(){if(!assertAdmin())return;await persistMany(state.players,true)}async function refreshSources(){if(!assertAdmin())return;buildState(state.players.map(toDb));await persistMany(state.players,true);render();renderRankEditor();refreshBestRecommendation();setStatus('Excel notes refreshed and custom ranks preserved.','ok')}
function refreshBestRecommendation(){const p=bestAvailable();currentRecommendation=p;if(!p){$('#recommendationBox').textContent='No available players left.';return}$('#recommendationBox').innerHTML=`<div class="recommendation-main">${esc(p.name)} <span class="pos ${p.pos}">${p.pos}</span></div><div class="recommendation-meta">${p.team} | Rank ${p.custom_rank} | Tier ${p.tier} | Score ${recommendationScore(p)}</div><div class="recommendation-reason">Best score based on rank, tier, roster need, and position scarcity.</div>`}function draftRecommended(){if(currentRecommendation)act('mine',currentRecommendation.id)}
function setupRankEditor(){renderRankTabs();renderRankEditor()}function openRankEditor(){if(!assertAdmin())return;$('#rankEditorView').hidden=false;document.body.classList.add('edit-rank-mode');renderRankTabs();renderRankEditor();$('#rankEditorView').scrollIntoView({behavior:'smooth'})}function closeRankEditor(){$('#rankEditorView').hidden=true;document.body.classList.remove('edit-rank-mode');render()}function renderRankTabs(){const wrap=$('#rankEditorTabs');wrap.innerHTML='';['ALL',...POSITIONS].forEach(pos=>{const b=document.createElement('button');b.className='rank-tab '+(rankEditor.active===pos?'active':'');b.textContent=pos;b.dataset.pos=pos;b.onclick=()=>{rankEditor.active=pos;renderRankTabs();renderRankEditor()};wrap.appendChild(b)})}function rankRows(){return state.players.filter(p=>rankEditor.active==='ALL'||p.pos===rankEditor.active).sort((a,b)=>a.custom_rank-b.custom_rank)}
function renderRankEditor(){const wrap=$('#rankEditorRows');if(!wrap)return;wrap.innerHTML=rankRows().map(p=>`<div class="rank-editor-row" data-rank-id="${p.id}"><div><span class="rank-drag">☰</span>${p.custom_rank}</div><div><b>${esc(p.name)}</b> <span class="pos ${p.pos}">${p.pos}</span></div><div>${esc(p.team)}</div><div><input class="rank-tier-input" type="number" value="${p.tier}" data-tier-id="${p.id}"></div><div><button class="note-btn" data-info-id="${p.id}">📝</button><button class="sleep-add-btn ${isManualSleeper(p.id)?'active':''}" data-sleep-id="${p.id}">${isManualSleeper(p.id)?'⭐':'☆'}</button></div></div>`).join('');$$('#rankEditorRows .rank-editor-row').forEach(r=>{r.addEventListener('pointerdown',rankPointerStart)});$$('.rank-tier-input').forEach(i=>i.onchange=()=>rankTierChange(i));$$('.note-btn').forEach(b=>b.onclick=e=>{e.stopPropagation();showPlayerInfo(b.dataset.infoId)});$$('.sleep-add-btn').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleManualSleeper(b.dataset.sleepId)})}
function pushUndo(){rankEditor.undoStack.push(state.players.map(p=>({id:p.id,custom_rank:p.custom_rank,tier:p.tier})));if(rankEditor.undoStack.length>20)rankEditor.undoStack.shift()}async function undoRankChange(){if(!assertAdmin())return;const snap=rankEditor.undoStack.pop();if(!snap)return;const m=new Map(snap.map(x=>[x.id,x]));state.players.forEach(p=>{const o=m.get(p.id);if(o){p.custom_rank=o.custom_rank;p.tier=o.tier}});await persistMany();render();renderRankEditor();refreshBestRecommendation()}async function rankTierChange(inp){if(!assertAdmin())return;pushUndo();const p=state.players.find(x=>x.id===inp.dataset.tierId);p.tier=Number(inp.value);await persistPlayer(p);render();renderRankEditor();refreshBestRecommendation()}
let ghost=null;function rankPointerStart(e){if(!isAdmin()||e.target.closest('input,button'))return;const row=e.currentTarget;rankEditor.dragId=row.dataset.rankId;pushUndo();rankEditor.dragging=true;row.classList.add('rank-placeholder');ghost=row.cloneNode(true);ghost.className='rank-drag-ghost';ghost.style.width=row.offsetWidth+'px';document.body.appendChild(ghost);moveGhost(e);const move=ev=>{ev.preventDefault();moveGhost(ev);const target=document.elementFromPoint(ev.clientX,ev.clientY)?.closest?.('.rank-editor-row');if(target&&target!==row&&target.parentNode===row.parentNode){const rect=target.getBoundingClientRect();target.parentNode.insertBefore(row,ev.clientY<rect.top+rect.height/2?target:target.nextSibling)}};const up=async()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);ghost?.remove();ghost=null;row.classList.remove('rank-placeholder');await commitLiveOrder()};document.addEventListener('pointermove',move,{passive:false});document.addEventListener('pointerup',up,{once:true})}function moveGhost(e){if(ghost){ghost.style.left=e.clientX+8+'px';ghost.style.top=e.clientY+8+'px'}}async function commitLiveOrder(){const ids=$$('#rankEditorRows .rank-editor-row').map(r=>r.dataset.rankId),slots=rankRows().map(p=>p.custom_rank).sort((a,b)=>a-b);if(rankEditor.active==='ALL')ids.forEach((id,i)=>{const p=state.players.find(x=>x.id===id);if(p)p.custom_rank=i+1});else ids.forEach((id,i)=>{const p=state.players.find(x=>x.id===id);if(p)p.custom_rank=slots[i]});await persistMany();render();renderRankEditor();refreshBestRecommendation()}
function rankSearchInput(){const q=key($('#rankSearch').value),box=$('#rankSuggestions');if(!q){box.hidden=true;box.innerHTML='';return}const matches=state.players.filter(p=>key(p.name).includes(q)||key(p.team).includes(q)||key(p.pos).includes(q)).sort((a,b)=>(key(a.name).startsWith(q)?0:1)-(key(b.name).startsWith(q)?0:1)||a.custom_rank-b.custom_rank).slice(0,8);box.innerHTML=matches.map(p=>`<button data-jump-id="${p.id}"><b>${esc(p.name)}</b><span>${p.pos} ${p.team} · Rank ${p.custom_rank}</span></button>`).join('')||'<div class="meta" style="padding:10px">No player found</div>';box.hidden=false;$$('#rankSuggestions [data-jump-id]').forEach(b=>b.onclick=()=>jumpToRankPlayer(b.dataset.jumpId))}function jumpToRankPlayer(id){if(rankEditor.active!=='ALL'){rankEditor.active='ALL';renderRankTabs();renderRankEditor()}setTimeout(()=>{const row=$(`#rankEditorRows .rank-editor-row[data-rank-id="${CSS.escape(id)}"]`);if(row){row.scrollIntoView({behavior:'smooth',block:'center'});row.classList.add('rank-jump-highlight');setTimeout(()=>row.classList.remove('rank-jump-highlight'),2200)}$('#rankSuggestions').hidden=true},80)}
function manualSleepers(){try{return JSON.parse(localStorage.getItem(MANUAL_SLEEPERS_KEY)||'{}')}catch{return{}}}function saveManualSleepers(o){localStorage.setItem(MANUAL_SLEEPERS_KEY,JSON.stringify(o))}function isManualSleeper(id){return !!manualSleepers()[id]}function toggleManualSleeper(id){if(!assertAdmin())return;const p=state.players.find(x=>x.id===id),o=manualSleepers();if(o[id])delete o[id];else o[id]={id:p.id,name:p.name,pos:p.pos,team:p.team,addedAt:new Date().toISOString()};saveManualSleepers(o);renderRankEditor();setStatus(o[id]?`${p.name} added to Sleeper Picks.`:`${p.name} removed from Sleeper Picks.`,'ok')}
async function loadSleeperMeta(){try{return await(await fetch('v41-sleepers.json?v=41')).json()}catch{return{excelSleeperNames:['Ashton Jeanty','Omarion Hampton','Tetairoa McMillan','Emeka Egbuka','Cam Skattebo','Caleb Williams','Jaxson Dart','Quinn Ewers'],copilotSleeperNames:['Luther Burden III','Ladd McConkey','Tucker Kraft','Dalton Kincaid','Isaiah Likely','Trey Benson','Zach Charbonnet','Blake Corum','Jaylen Warren','Christian Watson','Josh Downs','Parker Washington','Bucky Irving','Ray Davis','Rico Dowdle']}}}
async function showSleeperPicks(){const meta=await loadSleeperMeta(),excel=new Set((meta.excelSleeperNames||[]).map(key)),add=new Set((meta.copilotSleeperNames||[]).map(key)),manual=manualSleepers();const rows=state.players.filter(p=>!p.drafted).map(p=>{let source='';const info=getInfoForPlayer(p),k=key(p.name);if(manual[p.id])source='Manual Sleeper';else if(excel.has(k))source='Excel Sleeper Tab';else if(add.has(k))source='Added Sleeper';else if(p.custom_rank>=50&&p.custom_rank<=110&&!['K','DST'].includes(p.pos)&&/rookie|breakout|handcuff|upside|late flier|ppr|slot|goal-line|target/i.test(info['Key Player Notes & Analysis']||''))source='Added Sleeper';if(!source)return null;return{p,source,info}}).filter(Boolean).sort((a,b)=>a.p.custom_rank-b.p.custom_rank);$('#sleeperContent').innerHTML=`<h2>Remaining Sleeper Picks</h2><p class="muted">Excel sleeper tab, added sleepers, and manual stars from Edit Rankings. Drafted players are hidden.</p><div class="sleeper-list">${rows.map(({p,source,info})=>`<div class="sleeper-row"><div class="sleeper-main"><b>${esc(p.name)}</b><span class="pos ${p.pos}">${p.pos}</span><span>${p.team}</span></div><div class="sleeper-meta"><span>Rank ${p.custom_rank}</span><span>Tier ${p.tier}</span><span>${source}</span></div><p>${esc(info['Key Player Notes & Analysis']||'Added sleeper pick.')}</p></div>`).join('')||'<div class="sleeper-row">No remaining sleeper picks found.</div>'}</div>`;$('#sleeperDialog').showModal()}
function exportCsv(){const rows=[['pick','drafted_by','name','team','pos','custom_rank','tier','score','source_info'],...state.players.sort((a,b)=>a.custom_rank-b.custom_rank).map(p=>[p.pick||'',p.draftedBy||'',p.name,p.team,p.pos,p.custom_rank,p.tier,recommendationScore(p),JSON.stringify(getInfoForPlayer(p))])];const text=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='fantasy-war-room-export.csv';a.click();URL.revokeObjectURL(a.href)}function importAny(file){if(!assertAdmin()||!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(data.players){buildState(data.players);persistMany(state.players,true);render();renderRankEditor();refreshBestRecommendation()}}catch{setStatus('Import supports JSON backups in this full build.','warn')}};reader.readAsText(file)}
function selectionGuard(){document.addEventListener('selectstart',e=>{if(!e.target.closest('#search,input,textarea'))e.preventDefault()},true);document.addEventListener('contextmenu',e=>{if(!e.target.closest('#search,input,textarea'))e.preventDefault()},true)}
document.addEventListener('DOMContentLoaded',()=>init().catch(e=>{console.error(e);setStatus('Startup failed: '+(e.message||e),'bad')}));
