const STORE_KEY='fantasy-war-room-2026-v2';
const TABLE=window.SUPABASE_TABLE||'fantasy_players';
let state={players:[],activePos:'ALL'};
let sb=null, usingSupabase=false, saveTimer=null, realtimeChannel=null;
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function uid(name){return name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function configured(){return window.SUPABASE_URL && !window.SUPABASE_URL.includes('PASTE_') && window.SUPABASE_PUBLIC_KEY && !window.SUPABASE_PUBLIC_KEY.includes('PASTE_')}
async function init(){bind(); await connect(); render();}
async function connect(){
  if(configured() && window.supabase){sb=window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_PUBLIC_KEY); usingSupabase=true; await loadFromSupabase(); subscribeRealtime(); setStatus('Connected to Supabase. Edits sync for everyone.','ok');}
  else {usingSupabase=false; await loadLocalOrSeed(); setStatus('Supabase is not linked yet. Using local browser save only. Update config.js to sync for everyone.','warn');}
}
async function loadLocalOrSeed(){const saved=localStorage.getItem(STORE_KEY); if(saved){state=JSON.parse(saved)}else{const res=await fetch('data/seed-rankings.json'); const data=await res.json(); state.players=normalizeRows(data.players); state.activePos='ALL'; localSave();}}
async function loadFromSupabase(){const {data,error}=await sb.from(TABLE).select('*').order('custom_rank',{ascending:true}); if(error){setStatus('Supabase error: '+error.message,'bad'); await loadLocalOrSeed(); return;} if(!data || data.length===0){await loadLocalOrSeed(); setStatus('Supabase connected, but table is empty. Select Seed Supabase to publish the starter board.','warn'); return;} state.players=normalizeRows(data); state.activePos=state.activePos||'ALL'; localSave(false);}
function normalizeRows(rows){return rows.map(p=>({id:p.id||uid(p.name),name:p.name,team:p.team||'',pos:p.pos||'RB',custom_rank:Number(p.custom_rank??p.rank??999),tier:Number(p.tier??99),sources:p.sources||{},notes:p.notes||'',drafted:!!p.drafted,draftedBy:p.drafted_by??p.draftedBy??'',pick:p.pick??null,updated_at:p.updated_at||null}))}
function toDb(p){return {id:p.id||uid(p.name),name:p.name,team:p.team,pos:p.pos,custom_rank:Number(p.custom_rank),tier:Number(p.tier),sources:p.sources||{},notes:p.notes||'',drafted:!!p.drafted,drafted_by:p.draftedBy||'',pick:p.pick||null,updated_at:new Date().toISOString()}}
function bind(){['search','statusFilter','sortBy'].forEach(id=>$('#'+id).addEventListener('input',render)); $('#exportBtn').onclick=exportSave; $('#importJson').onchange=e=>importJson(e.target.files[0]); $('#importCsv').onchange=e=>importCsv(e.target.files[0]); $('#resetBtn').onclick=()=>{if(confirm('Clear local browser cache and reload? Supabase records are not deleted.')){localStorage.removeItem(STORE_KEY); location.reload();}}; $('#seedSupabaseBtn').onclick=seedSupabase; $('#cancelEdit').onclick=()=>$('#editDialog').close(); $('#editForm').addEventListener('submit',saveEdit)}
function setStatus(msg,cls){const el=$('#syncStatus'); if(!el)return; el.textContent=msg; el.className='sync-status '+cls}
function localSave(stamp=true){localStorage.setItem(STORE_KEY,JSON.stringify(state)); if(stamp && $('#lastSaved')) $('#lastSaved').textContent='Saved '+new Date().toLocaleTimeString()}
async function persistPlayer(p){localSave(); if(!usingSupabase||!sb)return; clearTimeout(saveTimer); saveTimer=setTimeout(async()=>{const {error}=await sb.from(TABLE).upsert(toDb(p)); if(error)setStatus('Supabase save failed: '+error.message,'bad'); else setStatus('Saved to Supabase. Everyone will see this update.','ok')},200)}
async function persistMany(players){localSave(); if(!usingSupabase||!sb)return; const {error}=await sb.from(TABLE).upsert(players.map(toDb)); if(error)setStatus('Supabase bulk save failed: '+error.message,'bad'); else setStatus('Bulk save complete in Supabase.','ok')}
async function seedSupabase(){if(!usingSupabase||!sb){alert('Add your Supabase URL and publishable/anon key in config.js first.'); return;} if(!confirm('Publish the current starter board to Supabase?'))return; await persistMany(state.players); await loadFromSupabase(); render();}
function subscribeRealtime(){ if(!sb)return; if(realtimeChannel) sb.removeChannel(realtimeChannel); realtimeChannel=sb.channel('fantasy-board-changes').on('postgres_changes',{event:'*',schema:'public',table:TABLE},payload=>{handleRealtime(payload)}).subscribe();}
function handleRealtime(payload){const row=payload.new||payload.old; if(!row)return; const id=row.id; if(payload.eventType==='DELETE'){state.players=state.players.filter(p=>p.id!==id)}else{const np=normalizeRows([row])[0]; const ix=state.players.findIndex(p=>p.id===id); if(ix>-1) state.players[ix]=np; else state.players.push(np);} localSave(false); render(); setStatus('Live update received from Supabase.','ok')}
function sourceAvg(p){const vals=Object.values(p.sources||{}).map(Number).filter(Boolean); return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:p.custom_rank}
function posRank(p){const same=state.players.filter(x=>x.pos===p.pos).sort((a,b)=>a.custom_rank-b.custom_rank); return p.pos+(same.findIndex(x=>x.id===p.id)+1)}
function getFiltered(){const q=$('#search').value.trim().toLowerCase(), status=$('#statusFilter').value; let arr=[...state.players]; if(state.activePos!=='ALL')arr=arr.filter(p=>p.pos===state.activePos); if(q)arr=arr.filter(p=>(p.name+' '+p.team+' '+p.pos).toLowerCase().includes(q)); if(status==='available')arr=arr.filter(p=>!p.drafted); if(status==='mine')arr=arr.filter(p=>p.draftedBy==='Me'); if(status==='drafted')arr=arr.filter(p=>p.drafted); const sort=$('#sortBy').value; arr.sort((a,b)=> sort==='tier'?(a.tier-b.tier||a.custom_rank-b.custom_rank):sort==='adp'?(sourceAvg(a)-sourceAvg(b)):sort==='pos'?(a.pos.localeCompare(b.pos)||a.custom_rank-b.custom_rank):a.custom_rank-b.custom_rank); return arr;}
function render(){renderChips(); const tbody=$('#board tbody'); tbody.innerHTML=''; for(const p of getFiltered()){const tr=document.createElement('tr'); if(p.drafted)tr.className='drafted-row'; tr.innerHTML=`<td><input class="rank-input" type="number" min="1" value="${p.custom_rank}" data-field="custom_rank" data-id="${p.id}"></td><td><input class="tier-input" type="number" min="1" value="${p.tier}" data-field="tier" data-id="${p.id}"></td><td><div class="player-name">${esc(p.name)}</div><div class="meta">${p.drafted?p.draftedBy==='Me'?'On my team':'Drafted by other':'Available'}</div></td><td><span class="pos ${p.pos}">${posRank(p)}</span></td><td>${esc(p.team)}</td><td>${renderSources(p)}</td><td>${esc(p.notes||'')}</td><td><div class="actions"><button class="mine" data-act="mine" data-id="${p.id}">Mine</button><button class="gone" data-act="gone" data-id="${p.id}">Gone</button><button class="edit" data-act="edit" data-id="${p.id}">Edit</button><button data-act="undo" data-id="${p.id}">Undo</button></div></td>`; tbody.appendChild(tr)} $$('.actions button').forEach(b=>b.onclick=()=>act(b.dataset.act,b.dataset.id)); $$('.rank-input,.tier-input').forEach(inp=>inp.onchange=()=>inlineUpdate(inp)); renderSidebars();}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function renderSources(p){return Object.entries(p.sources||{}).map(([k,v])=>`<div><strong>${v}</strong> <span class="meta">${esc(k)}</span></div>`).join('')||'<span class="meta">Manual</span>'}
function renderChips(){const wrap=$('#positionChips'); wrap.innerHTML=''; ['ALL','QB','RB','WR','TE'].forEach(pos=>{const b=document.createElement('button'); b.className='chip '+(state.activePos===pos?'active':''); b.textContent=pos; b.onclick=()=>{state.activePos=pos; render()}; wrap.appendChild(b)})}
function renderSidebars(){const mine=state.players.filter(p=>p.draftedBy==='Me').sort((a,b)=>(a.pick||999)-(b.pick||999)); $('#myTeam').innerHTML=mine.map(p=>`<li><strong>${esc(p.name)}</strong> <span class="meta">${p.pos} ${esc(p.team)}, Custom ${p.custom_rank}/Tier ${p.tier}</span></li>`).join('')||'<li class="meta">No picks yet</li>'; const drafted=state.players.filter(p=>p.drafted).sort((a,b)=>(a.pick||999)-(b.pick||999)); $('#draftedLog').innerHTML=drafted.slice(-24).reverse().map(p=>`<li>${esc(p.name)} <span class="meta">${esc(p.draftedBy)}</span></li>`).join('')||'<li class="meta">No drafted players yet</li>'; $('#availableCount').textContent=state.players.filter(p=>!p.drafted).length; $('#myCount').textContent=mine.length; $('#draftedCount').textContent=drafted.length;}
function inlineUpdate(inp){const p=state.players.find(x=>x.id===inp.dataset.id); if(!p)return; p[inp.dataset.field]=Number(inp.value); persistPlayer(p); render();}
function act(action,id){const p=state.players.find(x=>x.id===id); if(!p)return; if(action==='mine'){p.drafted=true;p.draftedBy='Me';p.pick=nextPick()} if(action==='gone'){p.drafted=true;p.draftedBy='Other';p.pick=nextPick()} if(action==='undo'){p.drafted=false;p.draftedBy='';p.pick=null} if(action==='edit')return openEdit(p); persistPlayer(p); render();}
function nextPick(){return Math.max(0,...state.players.map(p=>p.pick||0))+1}
function openEdit(p){$('#editId').value=p.id; $('#editName').value=p.name; $('#editTeam').value=p.team; $('#editPos').value=p.pos; $('#editRank').value=p.custom_rank; $('#editTier').value=p.tier; $('#editNotes').value=p.notes||''; $('#editDialog').showModal()}
function saveEdit(e){e.preventDefault(); const p=state.players.find(x=>x.id===$('#editId').value); if(!p)return; Object.assign(p,{name:$('#editName').value,team:$('#editTeam').value,pos:$('#editPos').value,custom_rank:+$('#editRank').value,tier:+$('#editTier').value,notes:$('#editNotes').value}); p.id=uid(p.name); persistPlayer(p); $('#editDialog').close(); render();}
function exportSave(){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'fantasy-war-room-save.json')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function importJson(file){if(!file)return; const r=new FileReader(); r.onload=async()=>{state=JSON.parse(r.result); state.players=normalizeRows(state.players||[]); await persistMany(state.players); render()}; r.readAsText(file)}
function importCsv(file){if(!file)return; const r=new FileReader(); r.onload=async()=>{mergeCsv(r.result); await persistMany(state.players); render()}; r.readAsText(file)}
function parseCsv(text){const rows=[];let row=[],cur='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++}else if(c==='"'){q=!q}else if(c===','&&!q){row.push(cur);cur=''}else if((c==='\n'||c==='\r')&&!q){if(cur||row.length){row.push(cur);rows.push(row);row=[];cur=''}if(c==='\r'&&n==='\n')i++}else cur+=c}if(cur||row.length){row.push(cur);rows.push(row)}return rows}
function mergeCsv(text){const rows=parseCsv(text).filter(r=>r.length); const headers=rows.shift().map(h=>h.trim().toLowerCase()); const idx=h=>headers.indexOf(h); rows.forEach(r=>{const name=r[idx('name')]||r[idx('player')]||''; if(!name)return; const id=uid(name); let p=state.players.find(x=>x.id===id||x.name.toLowerCase()===name.toLowerCase()); if(!p){p={id,name,team:'',pos:'RB',custom_rank:999,tier:99,sources:{},notes:'',drafted:false,draftedBy:'',pick:null}; state.players.push(p)} const source=r[idx('source')]||'Imported'; const rankVal=(idx('custom_rank')>-1?r[idx('custom_rank')]:r[idx('rank')]); if(rankVal){p.sources=p.sources||{}; p.sources[source]=+rankVal; p.custom_rank=+rankVal} if(idx('tier')>-1&&r[idx('tier')])p.tier=+r[idx('tier')]; if(idx('team')>-1&&r[idx('team')])p.team=r[idx('team')]; if(idx('pos')>-1&&r[idx('pos')])p.pos=r[idx('pos')]; if(idx('notes')>-1&&r[idx('notes')])p.notes=r[idx('notes')];}); state.players.sort((a,b)=>a.custom_rank-b.custom_rank)}
init();